server:
  port: 8082

spring:
  application:
    name: core-service
  datasource:
    url: jdbc:postgresql://localhost:5432/disaster_core
    username: postgres
    password: PIPL0050
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

ai:
  base-url: http://ai-service/api/v1/ai
notification:
  base-url: http://notification-service/api/v1/notify

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
